### ISSUE TITLE
TDP Low on Suspend/Resume Rog Ally

### ISSUE THREAD

**Issue by frohrbaugh** [aarron-lee/SimpleDeckyTDP#31]
Hi Aaron-Lee,

Appreciate all the work on this as it helps keep me on Linux for my Rog ally.

Question/issue, when I resume from suspend on bazzite OS with Rog Ally it tends to be a low tdp. It does fix after 10-20 seconds, or if I spam steam button and look at settings.

Is there a setting or configuration I'm missing? In addition, should I use temporarily set max tdp option. Or should I use Force Disable TDP on resume?

**Comment by aarron-lee** [comment]
So the issue you're describing is likely an ROG Ally-specific issue. The Ally already has a known issue where setting TDP immediately after resume from suspend usually doesn't work, I'm assuming your problem is related.

I don't know of a good workaround or solution because it's a ROG Ally specific issue, and I don't own a ROG Ally for to test + troubleshoot.

There's some BazziteOS Ally users on the Bazzite discord who might be able to help you more, they might have a better idea on workarounds + fixes for the Ally. See https://discord.bazzite.gg

**Comment by frohrbaugh** [comment]
All good thank you! I'll take a look around at that discord.

I was able to temporarily fix it by setting my max TDP to 40, reinstall the plugin at home without apps running, and then set "Temporarily use max TDP on resume."

Seems to be fine now but I'll keep looking around and double checking.

**Comment by aarron-lee** [comment]
thanks for the update, let me know if you find anything else.

If there's anything I can add to the plugin to help, I'd be open for it
