### ISSUE TITLE
TDP Limit is offset by a few digit

### ISSUE THREAD

**Issue by Panzer-II** [aarron-lee/SimpleDeckyTDP#34]
I'm currently running Bazzite OS on my ROG Ally, and for some reason, when I set my TDP to any amount 5W, 10W, 15W, it will always add in about 5W to it. I've already try disabling CPU Boost but that only took out like 1 - 2 W, in addition to running the Power Governor at Power Saving mode. But that would just make the APU run at 10W all the times, changing the TDP slider have no effect. If I use Balance Mode however, the TDP seem to get close to the limit, but is still off by about +2W, but it doesn't go above 15W. All of this was testing on Rog Ally Z1 Extreme, on Hades, Dark Souls Remastered, GTA IV.

**Comment by aarron-lee** [comment]
So you might be seeing TDP boost in action. TDP boost = temporary TDP boost when the device is under load. SimpleDeckyTDP (SDTDP) uses a very conservative TDP boost of 2W. For example, if you set 5W TDP, you may see moments where it temporarily goes up to 7W TDP.

That being said, another potential issue could be that the MangoHud performance overlay is being buggy. There have been some reports of it mis-reporting power consumption

If you want to verify the TDP vales being set, run this in terminal after setting TDP via SDTDP:

`sudo ryzenadj -i`

This will print out a tablet that looks like this:

```
CPU Family: Phoenix
SMU BIOS Interface Version: 14
Version: v0.15.0 
PM Table Version: 4c0008
|        Name         |   Value   |     Parameter      |
|---------------------|-----------|--------------------|
| STAPM LIMIT         |    8.000 | stapm-limit        |
| STAPM VALUE         |     3.797 |                    |
| PPT LIMIT FAST      |    10.000 | fast-limit         |
| PPT VALUE FAST      |     5.653 |                    |
| PPT LIMIT SLOW      |     8.000 | slow-limit         |
| PPT VALUE SLOW      |     4.129 |                    |
| StapmTimeConst      |     0.000 | stapm-time         |
| SlowPPTTimeConst    |     0.000 | slow-time          |
```

the STAPM LIMIT and SLOW LIMIT should match your TDP, while your FAST LIMIT will be +2 because of TDP boost.

if the values look correct, then TDP has been set correctly, and most likely Mangohud is buggy.

**Comment by Panzer-II** [comment]
thank for the reply, MangoHud seem to just display the wrong info, cause when I verfy using "sudo ryzenadj -i", the STAPM LIMIT and SLOW LIMIT should match the TDP limit I set.

**Comment by aarron-lee** [comment]
closing since it's working as-expected
